### ISSUE TITLE
Refactoring and low-level specialization

### ISSUE THREAD

**Issue by ernado** [ClickHouse/ch-go#120]
This repo should be kept mostly low-level, providing primitives on ClickHouse TCP protocol and Native format.

So, some higher-level abstractions should be extracted.
Also, some refactoring should be done based on acquired feedback and expertise, e.g. on using generics, json column type implementation and others.

This issue should track overall work.

- [ ] Support JSON column type
- [x] Rework DataTime64 to contain precision #130 
- [x] Rework Enum8, Enum16 to contain enum definition
- [ ] Add Apache header to all files

List is updating.

This will require some breaking changes.

**Comment by pkieltyka** [comment]
any updates on how to get JSON type support? thank you :)

**Comment by ernado** [comment]
This issue is outdated. 
Currently I have no plans to support json column.
