### ISSUE TITLE
 build:package net/netip is not in GOROOT

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ch-go#178]
hello, i am using clickhouse-go/v2:
```
github.com/ClickHouse/clickhouse-go/v2 v2.3.0
github.com/ClickHouse/ch-go@v0.47.3
```

and use go1.18.3 build it return error:
```
../../../go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/ipv4.go:5:2: package net/netip is not in GOROOT
```

seems that package net/netip is only valid in go1.19

**Comment by ernado** [comment]
https://go.dev/doc/go1.18#netip

It is in go1.18

**Comment by ernado** [comment]
Probably you are not using go1.18, because we have both go1.18 and go1.19 in CI/CD: https://github.com/ClickHouse/ch-go/runs/7937223598?check_suite_focus=true
