### ISSUE TITLE
Request: add option for struct/primitive scan

### ISSUE THREAD

**Issue by itziklavon** [ClickHouse/ch-go#180]
Hi, can we make this interface to be more generic? and work more like lets say sqlx works?
i.e pass in the struct/primitive we want to scan, and fill up the fields automatically
i think it will imrove the usabilty of this driver

**Comment by ernado** [comment]
Hi, probably this should be in https://github.com/ClickHouse/clickhouse-go?

As we have package for higher-level interaction, I'm not sure whether to add more generic things in ch-go.

**Comment by gingerwizard** [comment]
Already supported in clickhouse-go. This is a higher level construct and would likely mean adding reflection to ch-go, something imagine @ernado is not keen on

**Comment by ernado** [comment]
Please use clickhouse-go for this.
