### ISSUE TITLE
how to append data?

### ISSUE THREAD

**Issue by wangxuanyue** [ClickHouse/ch-go#192]
auto infer
```go
col := &proto.ColAuto{}
if err := col.Infer(proto.ColumnType("DateTime")); err != nil {
	fmt.Printf("Auto Infer Error: %s\n", err)
}

// how to append data to column???
col.append()???

**Comment by genzgd** [comment]
I believe you have to know (or determine) the type of the column that's returned and make the appropriate type assertion:

```go
inputCol := col.Data.(*proto.ColDateTime)
inputCol.Append(time.Now())
```

If you don't know in the type advance you could do this with a switch statement:
```go

switch col.Data.(type) {
case *proto.ColDateTime:
col.Data.(*proto.ColDateTime).Append(time.Now()
}
```

Most "dynamic" solutions for creating input columns are going to involve either large switch statements or reflection, so there will always be some moderate performance it.
