### ISSUE TITLE
proto.ColArr[proto.ColFixedStr] 

### ISSUE THREAD

**Issue by DataKhukhua** [ClickHouse/ch-go#212]
Hi, Why ColFixedStr  struct does not implements Arrayable interface  ?

**Comment by ernado** [comment]
Hi, you can still use `NewArray`:
```go
v := proto.NewArray[[]byte](&proto.ColFixedStr{Size: 10})

v.Append([][]byte{
	bytes.Repeat([]byte("a"), 10),
	bytes.Repeat([]byte("b"), 10),
	bytes.Repeat([]byte("c"), 10),
})
v.Append([][]byte{
	bytes.Repeat([]byte("d"), 10),
	bytes.Repeat([]byte("e"), 10),
	bytes.Repeat([]byte("f"), 10),
})
```

**Comment by ernado** [comment]
Your type will be
```
proto.ColArr[[]byte]
```
Not 
```
proto.ColArr[proto.ColFixedStr]
```

Like this:
```go
// Array returns new Array(FixedString).
func (c *ColFixedStr) Array() *ColArr[[]byte] {
	return &ColArr[[]byte]{
		Data: c,
	}
}
```

**Comment by ernado** [comment]
This test is for `Array(FixedString(10))`:
https://github.com/ClickHouse/ch-go/blob/20b750168af5f9766a7366292c137ebae8120fbb/query_test.go#L557-L583

Note that you still instantiate `&proto.ColFixedStr{Size: 10}` with `Size: 10`, `ColFixedStr` does not support size inference.

Also you can try `ColRawOf[[10]byte]` and it should work.
