### ISSUE TITLE
bug: write-deadline should be cleared if it gets set

### ISSUE THREAD

**Issue by jdef** [ClickHouse/ch-go#231]
in the client:
```go
		if err := c.conn.SetWriteDeadline(deadline); err != nil {
			return errors.Wrap(err, "set write deadline")
		}
```
.. it's not properly clearing the deadline, and so repeated use of the same connection ends up throwing up flush/timeout errors.

suggest something like a deferred call to `SetWriteDeadline(time.Time{})`, similar to what's done w/ `SetReadDeadline` elsewhere

**Comment by mshustov** [comment]
closed by https://github.com/ClickHouse/ch-go/pull/241 
feel free to reopen if it shows up again
