### ISSUE TITLE
page not found https://go-faster.org/docs/clickhouse/

### ISSUE THREAD

**Issue by cnmade** [ClickHouse/ch-go#239]
https://go-faster.org/docs/clickhouse/

The url list for the project introduction not available.
![image](https://user-images.githubusercontent.com/278153/213820575-c5a5efc2-2d10-47c2-9eb4-9f8b4a938f8a.png)

![image](https://user-images.githubusercontent.com/278153/213820595-f02e17d2-bbdd-46c8-8cd4-d38ef00bda5c.png)

**Comment by jkaflik** [comment]
@cnmade, thanks for this. I removed the invalid url.
