### ISSUE TITLE
ColMap support for LowCardinality(String) for both Keys and Values

### ISSUE THREAD

**Issue by yyfrankyy** [ClickHouse/ch-go#257]
I cannot find a proper way to define a `Map(LowCardinality(String), LowCardinality(String))`, does anybody try to convert a `map[string]string` into this?

by defining it as `proto.NewMap[string, string](new(proto.ColStr), new(proto.ColStr))`, clickhouse-server will raise an Exception, `Cannot convert: Map(String, String) to Map(LowCardinality(String), LowCardinality(String))`, server version 22.8

**Comment by dev-mraj** [comment]
You should try 

`proto.NewMap[string, string](new(proto.ColStr).LowCardinality(), new(proto.ColStr).LowCardinality())`
