### ISSUE TITLE
async_insert with ch-go

### ISSUE THREAD

**Issue by a-dot** [ClickHouse/ch-go#281]
Is it possible to use async_insert with ch-go? Every way I tried I always get this debug statement in the server logs:

`<Debug> executeQuery: Setting async_insert=1, but INSERT query will be executed synchronously (reason: insert query doesn't have inlined data)`

**Comment by ernado** [comment]
Hello, it is not possible or supported by `ch-go`.

For this mode, data should be fully inlined in query, i.e. you should set `Query.Body` to something like that:
```
INSERT INTO insert_select_testtable (*) VALUES (1, 'a', 1) ;
```

From https://clickhouse.com/docs/en/operations/settings/settings#async-insert:
> This makes sense only for insertion over HTTP protocol.

So there is no sense to support it in `ch-go`. To support it, we are forced to marshal data to text representation  (like in `VALUES (1, 'a', 1)`) and embed it to the query, which is out of scope for the `ch-go`.

**Comment by a-dot** [comment]
Excellent answer... Thank you very much!
