### ISSUE TITLE
Is there any way to create a column with LowCardinality(FixedString(8)) ?

### ISSUE THREAD

**Issue by jskcnsl** [ClickHouse/ch-go#302]
I have a column 'LowCardinality(FixedString(8))' in clickhouse, but only ColStr support LowCardinality. So now I can't insert into it by ch-go. 

Maybe I can copy LowCardinality() to ColFixStr ?

**Comment by ernado** [comment]
This is currently not possible because LowCardinality generic requires comparable values, and ColFixString value is byte slice.

Probably we can generate FixedStr8 (with [8]byte type), FixedStr16, FixedStr32, FixedStr64, FixedStr128, FixedStr256 and this will cover 80% cases. I'll take a look.

**Comment by jskcnsl** [comment]
I don't understand, why byte slice can't compare ? I didn't find the code about Comparable 😂

**Comment by ernado** [comment]
https://go.dev/blog/comparable

**Comment by ernado** [comment]
@jskcnsl please try `v0.57.0-alpha.0`

**Comment by jskcnsl** [comment]
Thanks! I will try it later
