### ISSUE TITLE
Or(v T) of Nullable[T] (in proto package) works improperly

### ISSUE THREAD

**Issue by edgro** [ClickHouse/ch-go#375]
### Describe the bug

Or(v T) of Nullable[T] (in proto package) works improperly

### Steps to reproduce
1. Use Or(v T) in parsing results of query
2. If underlying value is set, Or() will anyway return default value (v T), due to this bug

### Expected behaviour

Should return default value when underlying is not Set

### Code example
Looks like this:
```go
func (n Nullable[T]) Or(v T) T {
	if n.Set {
		return v
	}
	return n.Value
}
```
Should be:
```go
func (n Nullable[T]) Or(v T) T {
	if n.Set {
		return n.Value
	}
	return v
}
```
#### Environment
* Client version: 0.50, 0.61
* Language version: any
* OS: any

**Comment by ernado** [comment]
v0.61.2
