### ISSUE TITLE
what is the benefit of LowCardinaliy?

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ch-go#424]
if i have a column 
```
    env LowCardinality(String)
```

i could use proto.LowCardinaliy[proto.Str] and proto.Str to insert the column.

the LowCardinaliy would reduce bytes sent to clickhouse server but increase client memory usage.

in fact, if env is too slow that have only 2~3 bytes and the batch is very large,  the LowCardinaliy index would too long that could not reduce too much memory.

is it have any other benefit?

**Comment by serprex** [comment]
I assume #425 reflects fix related to this issue you're raising?
