### ISSUE TITLE
WATCHLIVE!* UFC 309 LiVe 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 FrEe BrOaDcAsT oN TV Guide & 𝐒𝐭𝐫𝐞𝐚𝐦𝐢𝐧𝐠 16 November 2024

### ISSUE THREAD

**Issue by mondien** [ClickHouse/ch-go#444]
The UFC's return to Madison Square Garden for UFC 309 will feature a stacked undercard.

The main event will see Jon Jones defend the UFC heavyweight title against former champion Stipe Miocic. The co-main event will see Michael Chandler and Charles Oliveira compete in a lightweight title eliminator rematch.

[🔴WATCH📺📱👉 UFC 309 LIVE STREAM](https://ufc.procast.live/?refd_by=clicktvnew)
[🔴WATCH📺📱👉 UFC 309 LIVE STREAM](https://ufc.procast.live/?refd_by=clicktvnew)
[🔴WATCH📺📱👉 UFC 309 LIVE STREAM](https://ufc.procast.live/?refd_by=clicktvnew)

Below is the TV channel, start time, and a free live stream option to watch the UFC 309 prelims.

Where to watch UFC 309 prelims for free
Live stream: Fubo | Hulu | ESPN+
Channel: ESPN News | FX
There are multiple ways to watch the UFC 309 prelims on Saturday. The prelims, starting at 8 p.m. ET will air on ESPN+. 

You can subscribe to ESPN+ for $11.99 on a monthly subscription and $119.99 on an annual subscription. For a limited time, get 12 months of ESPN+ for the price of 9 with the purchase of an annual plan.

It will also be streamed on Fubo which carries ESPN News and offers a free trial. It is also available on Hulu which offers FX via the Disney bundle.

Mauricio Ruffy (10-1), on a five-fight win streak, looks to go 2-0 in the octagon when he headlines the prelims against James Llontop. "Goku" (14-4) is on a two-fight losing streak after a strong run with FFC. 

Fan favorite Jim Miller, 2-2 in his last four fights, facing Damon Jackson, 1-3 in his last four fights. Meanwhile, light heavyweights are in action when sixth-ranked Nikita Krylov, on a three-fight win streak, faces eleventh-ranked Azamat Murzakanov, 4-0 in the UFC.

Ninth-ranked heavyweight Marcin Tybura (25-9), 2-2 in his last four fights, is a former M-1 Global heavyweight champion. He takes on Jhonata Diniz (7-1), a former kickboxing champion who is 3-0 in the octagon. The former Dana White's Contender Series standout was supposed to fight Derrick Lewis at the beginning of November, but the latter backed out.

On the early prelims, rising star Veronica Hardy (9-4-1), on a three-fight win streak, faces Eduarda Moura (10-1), who is 2-1 in the octagon. Also, New Jersey's Mickey Gall (7-6), on a three-fight losing streak, competes in his second fight in two years. He faces Ramiz Brahimaj (10-5), 2-2 in his last four fights.  

Where to watch UFC 309 main card
Live Stream: ESPN+
The UFC 308 main card is available via pay-per-view on ESPN+. The PPV price for UFC 309 is $79.99 for current subscribers. For a limited time, get 12 months of ESPN+ for the price of 9 with the purchase of an annual plan.

WATCH: UFC 309: Jon Jones vs. Stipe Miocic, exclusively on ESPN+

UFC 309 start time
Date: Saturday, November 16
Time: 10 p.m. ET (8 p.m. ET for prelims) | 7 p.m. PT
Location: Madison Square Garden, NY
UFC 309 will be at Madison Square Garden on November 16. The early prelims start at 6 p.m. ET, while the prelims are at 8 p.m. ET. The main card starts at 10 p.m. ET, and Jon Jones and Stipe Miocic should make their way to the octagon around 12:30 a.m. ET, depending on how long the undercard fights last. 

UFC 309 fight card
Main Card

Jon Jones (c) vs. Stipe Miocic for the UFC heavyweight title
Michael Chandler vs. Charles Oliveira; Lightweights
Viviane Araujo vs. Karine Silva; Flyweights
Bo Nickal vs. Paul Craig; Middleweights
Chris Weidman vs. Eryk Anders; Middleweights
Prelims

Mauricio Ruffy vs. James Llontop; Lightweights
Jonathan Martinez vs. Marcus McGhee; Bantamweights
Jim Miller vs. Damon Jackson; Lightweights
David Onama vs. Roberto Romero; Featherweights
Early Prelims

Mickey Gall vs. Ramiz Brahimaj; Welterweights
Marcin Tybura vs. Jhonata Diniz; Heavyweights
Bassil Hafez vs. Oban Elliot; Welterweights
Eduarda Moura vs. Veronica Hardy; Flyweights

**Comment by syghbvfu** [comment]
sdsadf

**Comment by keyasultana9** [comment]
dfgr
mmmmmmm

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://vidlab.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)

vvvvv

**Comment by mahfujmishu07** [comment]
v xvxvxc

**Comment by keyasultana9** [comment]
mmmmmmm

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://vidlab.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)

vvvvv

**Comment by cookieman3** [comment]
mmmmmmm

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://vidlab.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)

vvvvv
