### ISSUE TITLE
!(A.SSISTIR@TV)! UFC 309 Ao V.ivo GRÁTIS 16 Novembro 2024

### ISSUE THREAD

**Issue by DustinaCaldwell42** [ClickHouse/ch-go#521]
UFC 309: horário, onde assistir e card completo com Jon Jones x Miocic, Charles do Bronx e mais

<h3><a href="https://tinyurl.com/4j6ha5ua">➤►➤► UFC 309 Ao Vivo</a></h3>

<h3><a href="https://tinyurl.com/4j6ha5ua">➤►➤► Stipe Miocic x Jon Jones Ao Vivo</a></h3>

<h3><a href="https://tinyurl.com/4j6ha5ua">➤►➤► UFC 309: Jon Jones x Stipe Miocic Ao Vivo</a></h3>

<h3><a href="https://tinyurl.com/4j6ha5ua">➤►➤► UFC 309: Stipe Miocic x Jon Jones Ao Vivo</a></h3>

Saiba como assistir o UFC 309, show liderado por Jon Jones vs Stipe Miocic.
Que horas começa a luta do Jon Jones no UFC 309? Veja onde assistir.

Jon Jones x Stipe Miočić: confira horário e onde assistir ao UFC 309

OMadison Square Garden, em Nova York, será palco da maior luta entre pesos-pesados na história do Ultimate. O atual campeão Jon Jones tenta defender sua coroa pela primeira vez contra o ex-detentor do título Stipe Miocic na luta principal do UFC 309, neste sábado (16). 

Donos de dois dos maiores currículos do MMA, os lutadores estão prontos para proporcionar um espetáculo único para os fãs e aumentarem ainda mais seus legados no mundo das artes marciais mistas. 

Amplamente considerado como o maior lutador que já existiu na modalidade, Jones entra no confronto com o favoritismo ao seu lado segundo as casas de apostas, mas mantém os pés no chão quanto a isso. “É ótimo ser o favorito, mas o que realmente importa é quem estará com a mentalidade certa no sábado à noite”, comentou a jornalistas durante o Media Day. "Stipe é um vencedor, assim como eu. Ele é um dos maiores pesos-pesados de todos os tempos, e enfrentá-lo é uma honra. Porém, eu e minha equipe fizemos tudo certo. Estamos confiantes de que vamos vencer, e não apenas vencer, mas fazer isso de uma forma devastadora”.

Miocic enxerga o confronto como uma chance de retomar seu lugar como rei dos pesos-pesados e provar que ainda tem a resistência e a habilidade necessárias para competir no mais alto nível. “Eu só queria dar um descanso ao meu corpo e à minha mente, sabe? Recarregar as baterias”, explicou o ex-campeão ao ser questionado sobre os três anos longe do Octógono. “Agora estou pronto para entrar lá e fazer meu trabalho. Meu objetivo é ter uma grande apresentação e sair com a vitória”, complementou.  

Para o desafiante, medir forças com o “melhor dos melhores” também é uma oportunidade única em sua jornada no esporte. “Acho que essa é a maior luta da minha carreira até agora. Ele traz uma variedade de habilidades – socos, chutes, movimentos – e é muito inteligente no que faz. Será um confronto incrível. Jones é um adversário formidável e sei que preciso estar no meu melhor para superá-lo”.

Muito se debate sobre a possibilidade de ambos considerarem a aposentadoria após o combate deste sábado. Jones, atualmente com 37 anos, e Miocic, com 42, somam apenas duas aparições no Octógono nos últimos três anos. "Bones" derrotou Ciryl Gane em 2023 para conquistar o cinturão vago, enquanto Miocic foi destronado por Francis Ngannou em 2021. 

O campeão revela um certo incômodo com esse questionamento. “Desde que cheguei em Nova York, todos perguntam sobre o que farei depois de Stipe, mas não cheguei até aqui pensando no próximo oponente antes de vencer o que está à minha frente”, disse. “Meu foco agora é no sábado, em conseguir essa vitória e, quem sabe, pensar no próximo passo mais tarde”. 

Jones, porém, dá pistas de que há a possibilidade de continuar no esporte – especialmente se fizer superlutas. “Eu penso muito em fazer lutas por diversão depois desta. Não quero necessariamente carregar o peso do cinturão, quero lutas emocionantes, lutas que eu realmente quero fazer”. 

Um desses embates poderia ser contra o brasileiro Alex "Poatan" Pereira. O atual campeão peso meio-pesado e Jones já declararam interesse em se enfrentar nas redes sociais, e esse duelo é visto com bons olhos pelo norte-americano. "Faz sentido para mim, baseado em nossa idade e peso. Nós estamos sempre brincando um com o outro e é por isso que eu acho que enfrentá-lo seria divertido, pois nos respeitamos. Não somos melhores amigos, mas temos um relacionamento de muito respeito. Não seria uma luta promovida em cima de trash talk e outras porcarias que vemos por aí".

Miocic acompanha o campeão nesse raciocínio e prefere deixar para pensar em seu futuro depois de sábado. "Estou preocupado com a luta. Prefiro não me distrair pensando nas coisas que posso fazer no domingo. Só quero chegar lá e fazer aquilo que eu sei. Quando conseguir a vitória, falo para vocês o que farei depois". 

Independentemente do resultado, e do que acontecerá em seguida, o UFC 309 promete marcar um capítulo inesquecível para ambos e para o público. Com estilos de luta e históricos impressionantes, Jones e Miocic estão prontos para proporcionar um espetáculo único - e o vencedor irá aumentar ainda mais seu legado no esporte. 

Assista abaixo a análise de Vitor Miranda sobre o duelo.

Onde assistir ao UFC 309?
O UFC 309 terá transmissão completa do UFC Fight Pass, serviço de streaming oficial da companhia, que transmitirá o card preliminar e o principal. O card preliminar inteiro pode ser assistido no Canal GOAT, no YouTube.

Card completo do UFC 309:

Card Principal

Jon Jones x Stipe Miocic - pelo cinturão do peso pesado

Charles do Bronx x Michael Chandler - peso leve

Bo Nickal x Paul Craig - peso médio

Viviane Araújo x Karine Silva - peso mosca feminino

Mauricio Ruffy x James Llontop - peso leve

Card Preliminar

Jonathan Martinez x Marcus McGhee - peso galo

Chris Weidman x Eryk Anders - peso médio

Jim Miller x Damon Jackson - peso leve

David Onama x Roberto Romero - peso leve

Marcin Tybura x Jhonata Diniz - peso pesado

Mickey Gall x Ramiz Brahimaj - peso meio-médio

Bassil Hafez x Oban Elliott - peso meio-médio

Veronica Hardy x Eduarda 'Ronda' Moura - peso mosca feminino

**Comment by muktisarma74** [comment]
mmmmmmm

[![werx](https://github.com/user-attachments/assets/27f7afc8-550c-4887-b972-8cf06d38f318)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/35383578-0673-41d6-aac6-1c0eb2ca9082)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://go4s.wordpress.com/wp-content/uploads/2024/08/boxing.jpg)](https://vidlab.online/boxing)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/mmart.png)](https://vidlab.online/ufc)


[![werx](https://cdnmax.wordpress.com/wp-content/uploads/2024/06/night.png)](https://vidlab.online/ufc)


[![werx](https://github.com/user-attachments/assets/f6600a1c-457d-4159-b522-1c9e3cffec7d)](https://vidlab.online/ufc)

vvvvv
