### ISSUE TITLE
wATCH-VIDEOs-Pakistani-TikTok-Star-Imsha-Rehman-LEAKED-Video-Goes-Viral-Disappears-from-Social-Media-Trending-Now 

### ISSUE THREAD

**Issue by 2s1cyf6** [ClickHouse/ch-go#818]
### [🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖣𝗈𝗐𝗇𝗅𝗈𝖺𝖽 𝖭𝗈𝗐](https://all-viral-social.blogspot.com/2024/11/mr.html)

. 𝖳𝗁𝖾 𝗋𝖾𝖼𝗎𝗋𝗋𝖾𝗇𝗍 𝗍𝗁𝖾𝗆𝖾 𝗈𝖿 𝖫𝖾𝖺𝚔𝖾𝖽 𝗍𝖺𝗉𝖾𝗌 𝖺𝗇𝖽 𝗍𝗁𝖾 𝗌𝗎𝖻𝗌𝖾𝗊𝗎𝖾𝗇𝗍 𝖿𝖺𝗅𝗅𝗈𝗎𝗍 𝗌𝖾𝗋𝗏𝖾𝗌 𝖺𝗌 𝖺 𝗋𝖾𝗆𝗂𝗇𝖽𝖾𝗋 𝗈𝖿 𝗍𝗁𝖾 𝖿𝗋𝖺𝗀𝗂𝗅𝗂𝗍𝗒 𝗈𝖿 𝗋𝖾𝗉𝗎𝗍𝖺𝗍𝗂𝗈𝗇 𝗂𝗇 𝗍𝗁𝖾 𝖽𝗂𝗀𝗂𝗍𝖺𝗅 𝖾𝗋𝖺. 𝖠𝗌 𝗍𝗁𝖾 𝗅𝗂𝗇𝖾𝗌 𝖻𝖾𝗍𝗐𝖾𝖾𝗇 𝗉𝗋𝗂𝗏𝖺𝗍𝖾 𝖺𝗇𝖽 𝗉𝗎𝖻𝗅𝗂𝖼 𝗅𝗂𝖿𝖾 𝖼𝗈𝗇𝗍𝗂𝗇𝗎𝖾 𝗍𝗈 𝖻𝗅𝗎𝗋, 𝖼𝖾𝗅𝖾𝖻𝗋𝗂𝗍𝗂𝖾𝗌 𝗅𝗂𝗄𝖾 𝖯𝗋𝗂𝗌𝗈𝗇 𝖮𝖿𝖿𝗂𝖼𝖾𝗋𝖿𝗂𝗇𝖽 𝗍𝗁𝖾𝗆𝗌𝖾𝗅𝗏𝖾𝗌 𝖺𝗍 𝗍𝗁𝖾 𝗆𝖾𝗋𝖼𝗒 𝗈𝖿 𝗂𝗇𝗍𝖾𝗋𝗇𝖾𝗍 𝖼𝗁𝖺𝗍𝗍𝖾𝗋, 𝗐𝗁𝖾𝗋𝖾 𝖺 𝗋𝗎𝗆𝗈𝗋 𝖼𝖺𝗇 𝗂𝗀𝗇𝗂𝗍𝖾 𝖺 𝖿𝗂𝗋𝖾𝗌𝗍𝗈𝗋𝗆 𝗈𝖿 𝗌𝗉𝖾𝖼𝗎𝗅𝖺𝗍𝗂𝗈𝗇 𝖺𝗇𝖽 𝗃𝗎𝖽𝗀𝗆𝖾𝗇𝗍

𝖨𝗇 𝗍𝗁𝖾 𝖾𝗏𝖾𝗋 𝖾𝗏𝗈𝗅𝗏𝗂𝗇𝗀 𝗅𝖺𝗇𝖽𝗌𝖼𝖺𝗉𝖾 𝗈𝖿 𝖼𝖾𝗅𝖾𝖻𝗋𝗂𝗍𝗒 𝖼𝗎𝗅𝗍𝗎𝗋𝖾, 𝗍𝗁𝖾 𝖨𝗌𝗁𝗈𝗐𝗌𝗉𝖾𝖾𝖽𝗌𝖼𝖺𝗇𝖽𝖺𝗅 𝗎𝗇𝖽𝖾𝗋𝗌𝖼𝗈𝗋𝖾𝗌 𝗍𝗁𝖾 𝗋𝖾𝗅𝖾𝗇𝗍𝗅𝖾𝗌𝗌 𝗉𝗎𝗋𝗌𝗎𝗂𝗍 𝗈𝖿 𝗌𝖾𝗇𝗌𝖺𝗍𝗂𝗈𝗇𝖺𝗅𝗂𝗌𝗆, 𝖺 𝗉𝗎𝗋𝗌𝗎𝗂𝗍 𝗍𝗁𝖺𝗍 𝗈𝖿𝗍𝖾𝗇 𝖼𝗈𝗆𝖾𝗌 𝖺𝗍 𝗍𝗁𝖾 𝖾𝗑𝗉𝖾𝗇𝗌𝖾 𝗈𝖿 𝗍𝗋𝗎𝗍𝗁 𝖺𝗇𝖽 𝖽𝗂𝗀𝗇𝗂𝗍𝗒. 𝖠𝗌 𝗐𝖾 𝗇𝖺𝗏𝗂𝗀𝖺𝗍𝖾 𝗍𝗁𝖾 𝖼𝗈𝗆𝗉𝗅𝖾𝗑𝗂𝗍𝗂𝖾𝗌 𝗈𝖿 𝗍𝗁𝖾 𝖽𝗂𝗀𝗂𝗍𝖺𝗅 𝖺𝗀𝖾, 𝗍𝗁𝖾 𝗅𝗂𝗇𝖾 𝖻𝖾𝗍𝗐𝖾𝖾𝗇 𝖾𝗇𝗍𝖾𝗋𝗍𝖺𝗂𝗇𝗆𝖾𝗇𝗍 𝖺𝗇𝖽 𝖾𝗑𝗉𝗅𝗈𝗂𝗍𝖺𝗍𝗂𝗈𝗇 𝗋𝖾𝗆𝖺𝗂𝗇𝗌 𝗉𝖾𝗋𝗂𝗅𝗈𝗎𝗌𝗅𝗒 𝗍𝗁𝗂𝗇.

𝖠𝗌 𝗍𝗁𝖾 𝗌𝗂𝗍𝗎𝖺𝗍𝗂𝗈𝗇 𝗎𝗇𝖿𝗈𝗅𝖽𝗌, 𝗍𝗁𝖾 𝗍𝗋𝗎𝗍𝗁 𝗋𝖾𝗆𝖺𝗂𝗇𝗌 𝗌𝗁𝗋𝗈𝗎𝖽𝖾𝖽 𝗂𝗇 𝗆𝗒𝗌𝗍𝖾𝗋𝗒, 𝗅𝖾𝖺𝗏𝗂𝗇𝗀 𝗍𝗁𝖾 𝗉𝗎𝖻𝗅𝗂𝖼 𝗍𝗈 𝗉𝗈𝗇𝖽𝖾𝗋 𝗍𝗁𝖾 𝖺𝗎𝗍𝗁𝖾𝗇𝗍𝗂𝖼𝗂𝗍𝗒 𝗈𝖿 𝗍𝗁𝖾 𝗋𝗎𝗆𝗈𝗋𝗌. 𝖨𝗇 𝖺 𝗐𝗈𝗋𝗅𝖽 𝗐𝗁𝖾𝗋𝖾 𝖿𝖺𝗆𝖾 𝖺𝗇𝖽 𝗂𝗇𝖿𝖺𝗆𝗒 𝖺𝗋𝖾 𝗍𝗐𝗈 𝗌𝗂𝖽𝖾𝗌 𝗈𝖿 𝗍𝗁𝖾 𝗌𝖺𝗆𝖾 𝖼𝗈𝗂𝗇, 𝗍𝗁𝖾 𝗌𝖺𝗀𝖺 𝗈𝖿 𝖨𝗌𝗁𝗈𝗐𝗌𝗉𝖾𝖾𝖽𝗂𝗌 𝖺 𝗍𝖾𝗌𝗍𝖺𝗆𝖾𝗇𝗍 𝗍𝗈 𝗍𝗁𝖾 𝗉𝗈𝗐𝖾𝗋 𝗈𝖿 𝗌𝗈𝖼𝗂𝖺𝗅 𝗆𝖾𝖽𝗂𝖺 𝗍𝗈 𝗌𝗁𝖺𝗉𝖾 𝗇𝖺𝗋𝗋𝖺𝗍𝗂𝗏𝖾𝗌 𝖺𝗇𝖽 𝖼𝗁𝖺𝗅𝗅𝖾𝗇𝗀𝖾 𝗍𝗁𝖾 𝖻𝗈𝗎𝗇𝖽𝖺𝗋𝗂𝖾𝗌 𝗈𝖿 𝗉𝗋𝗂𝗏𝖺𝖼𝗒 𝖺𝗇𝖽 𝖼𝗈𝗇𝗌𝖾𝗇𝗍.

ISLAMABAD: An obscene video of another internet personality, Imsha Rehman emerged which went viral on social media drawing criticism from netizens.

The alleged explicit video of Instagram influencer and TikToker Imsha Rehman, claimed by social media users, surfaced where the Rehman star can be seen engaging in intimate moments with a friend.

The video, reportedly circulating on social media, allegedly showed Insha engaging with someone in obscene activities leading to intense trolling and bullying.

After her video went viral on social media, the internet influencer deactivated her Instagram and TikTok accounts.

The videos reportedly involve high-ranking civil servant Baltasar Ebang Engonga having sex with various women - including the wives of prominent officials - in his office.

Mr Engonga is head of the country's National Financial Investigation Agency and also a relative of the country's president.

He has not yet commented.

Vice-President Teodoro Obiang Mangue said any officials found engaging in sex acts at work would be suspended as this was a "flagrant violation of the code of conduct".

He has also ordered the installation of surveillance cameras in courts and ministries to combat "indecent and illicit acts".

A statement from the vice-president's office said the decision had been taken in the wake of the widely circulated videos which had "denigrated the image of the country".

It added that he had recommended opening an investigation.

The videos in question were leaked after Mr Engonga was arrested on separate corruption charges, state television TVGE said.

Last week, Vice-President Obiang said "pornographic videos" had been "flooding" social media and ordered telecoms companies to curb the spread.

Since then, the flow of internet traffic - particularly the downloading of images - has been severely disrupted in the country, people in Equatorial Guinea told the AFP news agency.

As head of the National Financial Investigation Agency, Mr Engonga works on tackling financial crimes such as money laundering.

Following the furore over the videos, Equatorial Guinea's chief prosecutor Anatolio Nzang Nguema told state TV that if Mr Engonga was found to have been "infected with a sexually transmitted disease" he would be prosecuted for an offence against "public health".

He is reportedly nicknamed "Bello" - Spanish for beautiful - on account of his good looks.

𝖠𝗌 𝗍𝗁𝖾 𝗌𝗂𝗍𝗎𝖺𝗍𝗂𝗈𝗇 𝗎𝗇𝖿𝗈𝗅𝖽𝗌, 𝗍𝗁𝖾 𝗍𝗋𝗎𝗍𝗁 𝗋𝖾𝗆𝖺𝗂𝗇𝗌 𝗌𝗁𝗋𝗈𝗎𝖽𝖾𝖽 𝗂𝗇 𝗆𝗒𝗌𝗍𝖾𝗋𝗒, 𝗅𝖾𝖺𝗏𝗂𝗇𝗀 𝗍𝗁𝖾 𝗉𝗎𝖻𝗅𝗂𝖼 𝗍𝗈 𝗉𝗈𝗇𝖽𝖾𝗋 𝗍𝗁𝖾 𝖺𝗎𝗍𝗁𝖾𝗇𝗍𝗂𝖼𝗂𝗍𝗒 𝗈𝖿 𝗍𝗁𝖾 𝗋𝗎𝗆𝗈𝗋𝗌. 𝖨𝗇 𝖺 𝗐𝗈𝗋𝗅𝖽 𝗐𝗁𝖾𝗋𝖾 𝖿𝖺𝗆𝖾 𝖺𝗇𝖽 𝗂𝗇𝖿𝖺𝗆𝗒 𝖺𝗋𝖾 𝗍𝗐𝗈 𝗌𝗂𝖽𝖾𝗌 𝗈𝖿 𝗍𝗁𝖾 𝗌𝖺𝗆𝖾 𝖼𝗈𝗂𝗇, 𝗍𝗁𝖾 𝗌𝖺𝗀𝖺 𝗈𝖿 𝖨𝗌𝗁𝗈𝗐𝗌𝗉𝖾𝖾𝖽𝗂𝗌 𝖺 𝗍𝖾𝗌𝗍𝖺𝗆𝖾𝗇𝗍 𝗍𝗈 𝗍𝗁𝖾 𝗉𝗈𝗐𝖾𝗋 𝗈𝖿 𝗌𝗈𝖼𝗂𝖺𝗅 𝗆𝖾𝖽𝗂𝖺 𝗍𝗈 𝗌𝗁𝖺𝗉𝖾 𝗇𝖺𝗋𝗋𝖺𝗍𝗂𝗏𝖾𝗌 𝖺𝗇𝖽 𝖼𝗁𝖺𝗅𝗅𝖾𝗇𝗀𝖾 𝗍𝗁𝖾 𝖻𝗈𝗎𝗇𝖽𝖺𝗋𝗂𝖾𝗌 𝗈𝖿 𝗉𝗋𝗂𝗏𝖺𝖼𝗒 𝖺𝗇𝖽 𝖼𝗈𝗇𝗌𝖾𝗇𝗍.

ISLAMABAD: An obscene video of another internet personality, Imsha Rehman emerged which went viral on social media drawing criticism from netizens.

The alleged explicit video of Instagram influencer and TikToker Imsha Rehman, claimed by social media users, surfaced where the Rehman star can be seen engaging in intimate moments with a friend.

The video, reportedly circulating on social media, allegedly showed Insha engaging with someone in obscene activities leading to intense trolling and bullying.

After her video went viral on social media, the internet influencer deactivated her Instagram and TikTok accounts.

The videos reportedly involve high-ranking civil servant Baltasar Ebang Engonga having sex with various women - including the wives of prominent officials - in his office.

Mr Engonga is head of the country's National Financial Investigation Agency and also a relative of the country's president.

He has not yet commented.

Vice-President Teodoro Obiang Mangue said any officials found engaging in sex acts at work would be suspended as this was a "flagrant violation of the code of conduct".

He has also ordered the installation of surveillance cameras in courts and ministries to combat "indecent and illicit acts".

A statement from the vice-president's office said the decision had been taken in the wake of the widely circulated videos which had "denigrated the image of the country".

It added that he had recommended opening an investigation.

The videos in question were leaked after Mr Engonga was arrested on separate corruption charges, state television TVGE said.

Last week, Vice-President Obiang said "pornographic videos" had been "flooding" social media and ordered telecoms companies to curb the spread.

Since then, the flow of internet traffic - particularly the downloading of images - has been severely disrupted in the country, people in Equatorial Guinea told the AFP news agency.

As head of the National Financial Investigation Agency, Mr Engonga works on tackling financial crimes such as money laundering.

Following the furore over the videos, Equatorial Guinea's chief prosecutor Anatolio Nzang Nguema told state TV that if Mr Engonga was found to have been "infected with a sexually transmitted disease" he would be prosecuted for an offence against "public health".

He is reportedly nicknamed "Bello" - Spanish for beautiful - on account of his good looks.

**Comment by badman8** [comment]
ghtyh

**Comment by Sheilahuarvey** [comment]
vbnvbn
