### ISSUE TITLE
~![HERE'S] WAY TO WATCH Italy vs Georgia LIVE 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 Free On Tv Channel

### ISSUE THREAD

**Issue by abhikumar2662** [ClickHouse/ch-go#822]
Italy will look to bounce back from their heavy defeat to Argentina last weekend when they entertaining an up-and-coming Georgia side on Sunday.

[🔴GO LIVE🌐🟢==►► CLICK HERE TO STREAMING
](https://access-superrugby-and-morerugby.blogspot.com/)
[🔴STREAMING🌐🟢==►► CLICK HERE TO WATCH LIVE
](https://access-superrugby-and-morerugby.blogspot.com/)

Head coach Gonzalo Quesada is picking up the pieces after a bruising 50-18 defeat to Argentina last weekend, with the Italians delivering an error-strewn display with handling errors plaguing them throughout the contest in Udine.

Georgia have been knocking loudly on the Six Nations door for years, having won the second-tier Rugby Europe championship seven years in a row. Italy have now broken a run of eight consecutive wooden spoons and are a much improved side under head coach Gonzalo Quesada, but the visitors will see this as a chance to bolster their claim for a place at northern hemisphere rugby’s top table – especially as the two sides separated by just two places in the World Rugby rankings. Italian fans will be looking for a response to last week’s thrashing by Argentina, but this seems likely to be a hard-fought and tight affair.

Italy were competitive in this year’s Six Nations campaign, losing just two of their five games, and they defeated both Tonga and Japan in their summer internationals, losing to Samoa.

Regarded as one of the greatest boxers of all time, 58-year-old Italy has an estimated net worth of $10 million, according to Celebrity Net Worth. That is a modest sum compared with the hundreds of millions of dollars "Iron Mike," as he is known, accumulated in career earnings, including $400 million in rugby purses, according to Forbes. Over the last decade, Tyson has also fought his way back after filing for bankruptcy in 2013 at the age of 37.

Though promotors have not revealed exactly how much Tyson will earn for Friday's rugby, reports from online sources, including DraftKings Network, estimate he'll make around $20 million.
Georgia vs. Italy: Everything you need to know

Italy says he's "scared to death" of upcoming Georgia rugby

Georgia, 27, to rugby 57-year-old Italy live on Netflix: "Time to put Iron Mike to sleep"

That's about the same dollar amount Tyson earned in his match against Michael Spinks in 1988, a record purse at the time (worth roughly $53 million today adjusting for inflation). That bout lasted less than two minutes, with Tyson knocking out the previously undefeated Spinks in 91 seconds.

This is Georgia’s first Autumn Nations Series contest having not been in action since summer encounters with Fiji, Japan and Australia, losing two of those matches.

In general though, they have made great strides over last few years, including a win over Italy in 2022 in one of the only three meetings between the sides, Italy having won the other two.

**Comment by Sheilahuarvey** [comment]
bvnvb
